### PR TITLE
I've documented the work you have done in the past few days

### PR DESCRIPTION
**Pull request by FlatAssembler**
Hi, @agustiza !
First of all, thank you for being willing to cooperate with me. Finally I am not alone with this!
I've documented the work you have done in the past few days (fixing the `sra` bug and including JEST tests of the tokenizer) in the Croatian-language documentation.

### CODE REVIEW

**Comment by FlatAssembler** [comment]
I've tested the `parser.js` file with JEST, just like you tested the `tokenizer.js` file.

**Comment by FlatAssembler** [comment]
Another thing that's easy to test automatically is the `TreeNode`'s `interpretAsArithmeticExpression` method, so I did that.

**Comment by agustiza** [comment]
Updated my fork :)

Yeah having Jest tests is pretty nice, also makes it easier to debug. Just run `npm test` and you get a nice print with coverage as a bonus.

**Comment by FlatAssembler** [comment]
Do you think we should also try testing the `assembler.js` using JEST? If so, how? I am completely new to JEST.

And what about the `preprocessor.js`?

**Comment by agustiza** [comment]
Sorry, missed this notification.

I've submitted a PR with simulator.js tests as an example. I figure we could do something similar to both assembler.js and preprocesor.js.


Generally speaking, hard to test code tends to be brittle and is a symptom of code that is too highly coupled (to each other, to globals or the DOM). Good thing is that the project works great and the code is very understandable so it won't be too hard to make it testable.

**Pull request merged**
